spring:
  datasource:
    url: jdbc:oracle:thin:@//192.168.1.11:1521/xe
    username: main_dba
    password: main_dba
    driver-class-name: oracle.jdbc.OracleDriver
  http:
    converters:
      preferred-json-mapper: jackson